-- Obsolete migration.
-- This file is intentionally a no-op because the payment lifecycle behavior
-- it was meant to introduce is already implemented elsewhere.
-- It is not part of the live order flow.
-- Current canonical flow: Pending Payment -> Paid -> Ready -> Completed.
